main/urls.py
from django.conf.urls import url

from . import views

app_name = 'main'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^list',views.list,name='list'),
    url(r'^profile',views.profile,name='profile'),
    url(r'^history',views.history,name='history'),
    url(r'^login',views.login_regis_view,name='login_regis'),
    url(r'^doregis',views.do_regis,name='regis'),
    url(r'^dologin',views.do_login,name='login'),
    url(r'^profile',views.profile,name='profile'),
    url(r'^history',views.history,name='history'),
]

pigpugpong/main/urls.py
from django.conf.urls import url

from . import views

app_name = 'main'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^list',views.list,name='list'),
    url(r'^profile',views.profile,name='profile'),
]

pigpugpong/pigpugpong/urls.py
from django.conf.urls import url,include
from django.contrib import admin

app_name = 'pigpugpong'

urlpatterns = [
    url(r'^',include('main.urls')),
    url(r'^admin/', admin.site.urls),
]

pigpugpong/urls.py
from django.conf.urls import url,include
from django.contrib import admin

app_name = 'pigpugpong'

urlpatterns = [
    url(r'^',include('main.urls')),
    url(r'^admin/', admin.site.urls),
]

main/models.py
import datetime
from django.db import models

class Accounts (models.Model) :
    user_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=15)
    email = models.CharField(max_length=30)
    password = models.CharField(max_length=20)

    def __str__(self):
        return u'id : %s ( %s )' % (self.user_id , self.username)
    class Meta:
        db_table = "accounts"

class Order (models.Model) :
    order_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey('Accounts')
    package_id = models.ForeignKey('Package')
    date_order = models.DateTimeField()
    date_paid = models.DateTimeField()
    date_count = models.IntegerField(3);
    status = models.BooleanField(default=False)
    top_up_code = models.CharField(max_length=100)
    payment_code = models.CharField(max_length=30)

    def __str__(self):
        return u'id : %s' % self.order_id
#
# class User_Wallet (models.Model) :
#     user_id =
#     money =
#
class Package (models.Model) :
    package_id = models.AutoField(primary_key=True)
    top_up_type_id = models.ForeignKey('Top_Up_Type')
    value = models.IntegerField();
    price = models.IntegerField();

    def __str__(self):
        return u'id : %s' % self.package_id

class Top_Up_Type (models.Model) :
    top_up_type_id = models.AutoField(primary_key=True)
    TYPE_NAME_CHOICES = (
        ('STEAM','steam'),
        ('LINE','line'),
        ('PLAY_STATION','play_station')
    )
    type_name = models.CharField(max_length=20,choices=TYPE_NAME_CHOICES)
    image_path = models.CharField(max_length=100)

    def __str__(self):
        return u'id : %s ( %s )' % (self.top_up_type_id ,self.type_name)

pigpugpong/main/models.py
import datetime
from django.db import models

class Accounts (models.Model) :
    user_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=15)
    email = models.CharField(max_length=30)
    password = models.CharField(max_length=20)

class Order (models.Model) :
    order_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey('Accounts')
    package_id = models.ForeignKey('Package')
    date_order = models.DateTimeField()
    date_paid = models.DateTimeField()
    date_count = models.IntegerField(3);
    status = models.BooleanField(default=False)
    top_up_code = models.CharField(max_length=13)
    payment_code = models.CharField(max_length=13)
#
# class User_Wallet (models.Model) :
#     user_id =
#     money =
#
class Package (models.Model) :
    package_id = models.AutoField(primary_key=True)
    top_up_type_id = models.ForeignKey('Top_Up_Type')
    value = models.IntegerField();
    price = models.IntegerField();

class Top_Up_Type (models.Model) :
    top_up_type_id = models.AutoField(primary_key=True)
    TYPE_NAME_CHOICES = (
        ('STREAM','stream'),
        ('LINE','line'),
        ('PLAY_STATION','play_station'),
        ('TOP_UP_WALLET','top_up_wallet')
    )
    type_name = models.CharField(max_length=20,choices=TYPE_NAME_CHOICES)
    image_path = models.CharField(max_length=100)

main/views.py
from django.shortcuts import render
from django.db import connection
from main.models import Accounts

from .models import Accounts

# Create your views here.
def index( request ) :
    return render( request,'index.html' )

def list( request ) :
    key = request.POST[ 'key' ]
    return render( request,'list.html', { 'key':key } )

def profile(request) :
    account = Accounts.objects.get(username='minsteric.smile')

def history(request) :
    account = Accounts.objects.get(username='minsteric.smile')
    return render(request,'history.html', {'account':account})

def login_regis_view( request ) :
    return render(request, 'login_register_view.html')

def do_login( request ) :
    if request.method == "POST" :
        _login_key = request.POST.get( "login_key" )
        _login_pass = request.POST.get( "login_password" )

        row = Accounts.objects.filter( username=_login_key, password=_login_pass )
        user = None
        if not row:
            row = Accounts.objects.filter( email=_login_key, password=_login_pass )

        if not row :
            request.session['error'] = "user not found"
            return render( request, 'login_register_view.html' )
        user = row[0]

        request.session['username'] = user.username

    return render( request, 'index.html' )

def do_regis( request ):

    _username = request.POST.get( "regis_username", "" )
    _email = request.POST.get( "regis_email", "" )
    _pass = request.POST.get( " regis_password", "" )
    _con_pass = request.POST.get( "regis_confirmpassword", "" )

    # if _pass == _con_pass:
    # if _pass != _con_pass:

    # new_account = Accounts()
    return HttpResponseRedirect('/login/')

def test_view( request ) :
    return render( request, "test.html" )

pigpugpong/main/views.py
from django.shortcuts import render

from .models import Accounts

# Create your views here.
def index(request) :
    return render(request,'index.html')

def list(request) :
    key = request.POST['key']
    return render(request,'list.html',{'key':key})

def profile(request) :

    account = Accounts.objects.get(username='minsteric.smile')

    return render(request,'profile.html', {'account':account})

# def profile(request) :
#     return render(request,'profile.html', {'key':key})

main/templates/history.html
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en">
<!--<![endif]-->
<!-- HEAD SECTION -->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
    <title>PIG PUG PONG TOP-UP</title>
    <!--GOOGLE FONT -->
    {% load staticfiles %}
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <!--BOOTSTRAP MAIN STYLES -->
    <link href="{% static 'assets/css/bootstrap.css' %}" rel="stylesheet" />
    <!--FONTAWESOME MAIN STYLE -->
    <link href="{% static 'assets/css/font-awesome.min.css' %}" rel="stylesheet" />
    <!-- <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css"> -->
    <!--SLIDER CSS CLASES -->
    <link href="{% static 'assets/Slides-SlidesJS-3/examples/playing/css/slider.css' %}" rel="stylesheet" />
    <!--CUSTOM STYLE -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/css/history.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/css/profile.css' %}" rel="stylesheet" />
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<!--END HEAD SECTION -->
<body>
    <!-- NAV SECTION -->
    <div class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'main:index' %}">PIGPUGPONG</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <!-- <li><a href="index.html">HOME</a></li>
                    <li><a href="about.html">ABOUT</a></li>
                    <li><a href="services.html">SERVICES</a></li>
                    <li><a href="pricing.html">PRICING</a></li>
                    <li><a href="gallery.html">GALLERY</a></li>
                    <li><a href="contact.html">CONTACT</a></li> -->
                </ul>
            </div>
        </div>
    </div>
    <!--END NAV SECTION -->
    <!-- HOME SECTION -->
    {% include "profile.html" %}
    <div class="container right">

      <div class="row card-detail">
        <div class="col-xs-2">
          <img class="stricker" src="../static/images/psn.png" >
        </div>
        <div class="col-xs-6">
          <p>Description</p>
        </div>
        <div class="col-xs-2 status-active">
          <p>Status</p>
        </div>
        <div class="col-xs-2">
          <p>Date</p>
        </div>
      </div>
      <div class="row card-detail">
        <div class="col-xs-2">
          <img class="stricker" src="../static/images/psn.png" >
        </div>
        <div class="col-xs-6">
          <p>Description</p>
        </div>
        <div class="col-xs-2 status-complete">
          <p>Status</p>
        </div>
        <div class="col-xs-2">
          <p>Date</p>
        </div>
      </div>
      <div class="row card-detail">
        <div class="col-xs-2">
          <img class="stricker" src="../static/images/psn.png" >
        </div>
        <div class="col-xs-6">
          <p>Description</p>
        </div>
        <div class="col-xs-2 status-active">
          <p>Status</p>
        </div>
        <div class="col-xs-2">
          <p>Date</p>
        </div>
      </div>
    <!--END HOME SECTION -->

    <!-- JAVASCRIPT FILES PLACED AT THE BOTTOM TO REDUCE THE LOADING TIME  -->
    <!-- CORE JQUERY LIBRARY -->
    {% load static %}
    <script src="{% static 'assets/js/jquery.js' %}"></script>
    <!-- CORE BOOTSTRAP LIBRARY -->
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <!-- SLIDER SCRIPTS LIBRARY -->
    <script src="{% static 'assets/Slides-SlidesJS-3/examples/playing/js/jquery.slides.min.js' %}"></script>
    <script src="{% static 'assets/js/profile.js' %}"></script>
    <!-- CUSTOM SCRIPT-->
    <script>
        $(document).ready(function () {
            $('#slides').slidesjs({
                width: 940,
                height: 528,
                play: {
                    active: true,
                    auto: true,
                    interval: 4000,
                    swap: true
                }
            });
        });
    </script>
</body>
</html>

main/templates/index.html
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en">
<!--<![endif]-->
<!-- HEAD SECTION -->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
    <title>PIG PUG PONG TOP-UP</title>
    <!--GOOGLE FONT -->
    {% load staticfiles %}
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <!--BOOTSTRAP MAIN STYLES -->
    <link href="{% static 'assets/css/bootstrap.css' %}" rel="stylesheet" />
    <!--FONTAWESOME MAIN STYLE -->
    <link href="{% static 'assets/css/font-awesome.min.css' %}" rel="stylesheet" />
    <!-- <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css"> -->
    <!--SLIDER CSS CLASES -->
    <link href="{% static 'assets/Slides-SlidesJS-3/examples/playing/css/slider.css' %}" rel="stylesheet" />
    <!--CUSTOM STYLE -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<!--END HEAD SECTION -->
<body>
    <!-- NAV SECTION -->
    <div class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'main:index' %}">PIGPUGPONG</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <!-- <li><a href="index.html">HOME</a></li>
                    <li><a href="about.html">ABOUT</a></li>
                    <li><a href="services.html">SERVICES</a></li>
                    <li><a href="pricing.html">PRICING</a></li>
                    <li><a href="gallery.html">GALLERY</a></li>
                    <li><a href="contact.html">CONTACT</a></li> -->
                </ul>
            </div>
        </div>
    </div>
    <!--END NAV SECTION -->
    <!-- HOME SECTION -->

    <div class="container">
        <div class="row main-low-margin text-center">
            <div class="col-md-4 col-sm-4">
              <form action = "{% url 'main:list' %}" method = "post">{% csrf_token %}
                <div class="circle-body"><button class="fa fa-steam-square fa-5x  icon-set hidebut" type = "submit"></button></div>
                <input name = "key" value = "Steam" type = "hidden"></input>
              </form>
              <h3>Steam Wallet</h3>
            </div>
            <div class="col-md-4 col-sm-4">
              <form action = "{% url 'main:list' %}" method = "post">{% csrf_token %}
                <div class="circle-body"><button class="fa fa-dollar fa-5x  icon-set hidebut" type = "submit"></button></div>
                <input name = "key" value = "Line" type = "hidden"></input>
              </form>
              <h3>LINE coin</h3>
            </div>
            <div class="col-md-4 col-sm-4">
              <form action = "{% url 'main:list' %}" method = "post">{% csrf_token %}
                <div class="circle-body"><button class="fa fa-youtube-play   fa-5x  icon-set hidebut" type = "submit"></button></div>
                <input name = "key" value = "PSN" type = "hidden"></input>
              </form>
              <h3>PSN Wellet</h3>
            </div>
        </div>
    </div>
    <div class="space-bottom"></div>

    <!--END HOME SECTION -->
    <!--FOOTER SECTION -->
    <div id="footer">
        <div class="row">
            <div class="col-md-4">
                <h4>Quick Information :</h4>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                        Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                </p>
                <button type="submit" class="btn btn-primary">Get Quote</button>
            </div>
            <div class="col-md-4">
                <h4>Need Help ? Write Us. </h4>
                <hr>
                <form>
                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                            <div class="form-group">
                                <input type="text" class="form-control" required="required" placeholder="Name">
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <div class="form-group">
                                <input type="text" class="form-control" required="required" placeholder="Email address">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <div class="form-group">
                                <textarea name="message" id="message" required="required" class="form-control" rows="3" placeholder="Message"></textarea>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Submit Request</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-4">
                <a href="#"><i class="fa fa-facebook-square fa-3x color-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter-square fa-3x color-twitter"></i></a>
                <a href="#"><i class="fa fa-google-plus-square fa-3x color-google-plus"></i></a>
                <a href="#"><i class="fa fa-linkedin-square fa-3x color-linkedin"></i></a>
                <a href="#"><i class="fa fa-pinterest-square fa-3x color-pinterest"></i></a>
                <hr>
                <p>
                    103, New Street,<br>
                    New York, USA.<br>
                    Call: +23-00-89-009<br>
                    Email: demo@yourdomain.com<br>
                </p>
                2014 www.yourdomain.com | All Right Reserved
            </div>
        </div>
    </div>
    <!--END FOOTER SECTION -->
    <!-- JAVASCRIPT FILES PLACED AT THE BOTTOM TO REDUCE THE LOADING TIME  -->
    <!-- CORE JQUERY LIBRARY -->
    {% load static %}
    <script src="{% static 'assets/js/jquery.js' %}"></script>
    <!-- CORE BOOTSTRAP LIBRARY -->
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <!-- SLIDER SCRIPTS LIBRARY -->
    <script src="{% static 'assets/Slides-SlidesJS-3/examples/playing/js/jquery.slides.min.js' %}"></script>
    <!-- CUSTOM SCRIPT-->
    <script>
        $(document).ready(function () {
            $('#slides').slidesjs({
                width: 940,
                height: 528,
                play: {
                    active: true,
                    auto: true,
                    interval: 4000,
                    swap: true
                }
            });
        });
    </script>
</body>
</html>

main/templates/login_register_view.html
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en">
<!--<![endif]-->
<!-- HEAD SECTION -->
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <!--[if IE]>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <![endif]-->
  <title>PIG PUG PONG TOP-UP</title>
  <!--GOOGLE FONT -->
  {% load staticfiles %}
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <!--BOOTSTRAP MAIN STYLES -->
  <link href="{% static 'assets/css/bootstrap.css' %}" rel="stylesheet" />
  <!--FONTAWESOME MAIN STYLE -->
  <link href="{% static 'assets/css/font-awesome.min.css' %}" rel="stylesheet" />
  <!-- <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css"> -->
  <!--SLIDER CSS CLASES -->
  <link href="{% static 'assets/Slides-SlidesJS-3/examples/playing/css/slider.css' %}" rel="stylesheet" />
  <!--CUSTOM STYLE -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />

  <link href="{% static 'assets/css/style-loginregis.css' %}" rel="stylesheet" />

  <script src="{% static 'assets/js/jquery.js' %}"></script>
  <!-- CORE BOOTSTRAP LIBRARY -->
  <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
  <!-- SLIDER SCRIPTS LIBRARY -->
  <script src="{% static 'assets/Slides-SlidesJS-3/examples/playing/js/jquery.slides.min.js' %}"></script>
  <!-- CUSTOM SCRIPT-->

  <!-- Import for use DatePicker  -->
  <!-- <script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>

  <script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" /> -->

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
</head>
<!--END HEAD SECTION -->
<body>
  <!-- NAV SECTION -->
  <div class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <a class="navbar-brand ppp" href="{% url 'main:index' %}">PIGPUGPONG</a>
      </div>
      <div class="navbar-collapse collapse">
        <form action="{% url 'main:login' %}" method="post">
          {% csrf_token %}
          <ul class="nav navbar-nav navbar-right">
            <div class="row" style="padding-top: 6px; padding-bottom: 6px">
              <div class="col-md-4">
                <li>
                  <div class="row"><input class="form-control" type="text" id="login_email" placeholder="username / email" name="login_key"></div>
                </li>
              </div>
              <div class="col-md-1"></div>
              <div class="col-md-4">
                <li>
                  <div class="row"><input class="form-control" type="password" id="login_password" placeholder="password" name="login_password"></div>
                </li>
              </div>
              <div class="col-md-1"></div>
              <div class="col-md-2">
                <li>
                  <div class="row"><button type="submit" class="btn btn-primary">Login</button></div>
                </li>
              </div>
            </div>

            <!-- <li><a href="services.html">SERVICES</a></li>
            <li><a href="pricing.html">PRICING</a></li>
            <li><a href="gallery.html">GALLERY</a></li>
            <li><a href="contact.html">CONTACT</a></li> -->
          </ul>
        </form>
      </div>
    </div>
  </div>
  <!--END NAV SECTION -->
  <!-- HOME SECTION -->


  <div class="container">
    <div class="row">
      <div class="col-md-6 jumbotron">

        <h1 class="ppp">Sign Up</h1>
        <!-- <form name="submit_form" id="submit_form" action="/login/regis/" method="post"> -->
        <!-- {% csrf_token %} -->
        <div class="row">
          <input type="text" class="mar form-control" required="required"  id="regis_username" name="regis_username" placeholder="Username">
          <input type="text" class="mar form-control" required="required"  id="regis_email" name="regis_email" placeholder="E-mail">
          <input class="mar form-control" type="password" id="regis_password" name="regis_password" placeholder="Password">
          <input class="mar form-control" type="password" id="regis_confirmpassword" name="regis_confirmpassword" placeholder="Confirm Password">
        </div>
        <div class="row text-right" >
          <button type="submit" class="btn btn-primary">Sign Up</button>
        </div>
        <!-- </form> -->


      </div>
      <div class="col-md-6">
        For logo or any event!!!
      </div>
    </div>
  </div>
  <div class="space-bottom"></div>
  <!--END HOME SECTION -->

  <!-- JAVASCRIPT FILES PLACED AT THE BOTTOM TO REDUCE THE LOADING TIME  -->
  <!-- CORE JQUERY LIBRARY -->


  <script>
  $(document).ready(function () {
    $('#slides').slidesjs({
      width: 940,
      height: 528,
      play: {
        active: true,
        auto: true,
        interval: 4000,
        swap: true
      }
    });

  });

  </script>

</body>
</html>

main/templates/profile.html
<div class="container width-200" id="edit">

  <!-- bio -->
    <div class="col-md-12 col-sm-12 image-container">
      <div class="form-group">
        <img class="profile" src = "../static/images/profile.jpg" alt="100">
      </div>
      <div class="form-group">
        <span class="glyphicon glyphicon-user bold" aria-hidden="true"></span> {{account.username}}
        <br>
        <span class="glyphicon glyphicon-usd bold" aria-hidden="true"></span> 343 baht
        <br>
        <span class="glyphicon glyphicon-star bold" aria-hidden="true"></span> 37 point
        <br>
        <form id="edit-profile">
          <button type="submit" class="btn btn-success">Edit</button>
        </form>
      </div>
    </div>
</div>

<div class="container width-200" id="save_change">

  <!-- bio -->
    <div class="col-md-12 col-sm-12 image-container">
      <div class="form-group">
        <img class="profile" src = "../static/images/profile.jpg" alt="100">
        <input class = "browse" name = "key" value = "Line" type = "file"></input>
      </div>
      <div class="form-group">
        <span class="glyphicon glyphicon-user bold" aria-hidden="true"></span> Username
        <input type="text" class="form-control" value = {{account.username}}>
      </div>
      <div class="form-group">
        <span class="glyphicon glyphicon-envelope bold" aria-hidden="true"></span> Email
        <input type="text" class="form-control" value = {{account.email}}>
      </div>
      <div class="form-group">
        <form id="save-profile">
          <button type="submit" class="btn btn-primary">Save Change</button>
        </form>
      </div>
    </div>

</div>

main/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>login test</title>
</head>
<body>
  <meta charset="utf-8">
  <h1>LOGIN DONE<h1>
  </meta>
</body>